receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:

exporters:
  debug:
    verbosity: detailed

  prometheus:
    endpoint: "0.0.0.0:8889"
    namespace: "todo_app"

  # Template for Datadog
  # otlp/datadog:
  #   endpoint: "https://trace.agent.datadoghq.com"
  #   headers:
  #     "DD-API-KEY": "${DD_API_KEY}"

  # Template for Elasticsearch
  # otlp/elasticsearch:
  #   endpoint: "${ES_ENDPOINT}"
  #   headers:
  #     "Authorization": "ApiKey ${ES_API_KEY}"

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug] # Add otlp/datadog, otlp/elasticsearch here
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, prometheus] # Add otlp/datadog, otlp/elasticsearch here
